name: Example workflow

on:
  push: 
    branches:
      [ main ]

env:
  message: "Hello env"

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - uses: MauricioNTT/example-action@main
        with:
          message: Hello Inputs
