name: Example workflow

on:
  push: 
    branches:
      [ main ]



jobs:
  hello:
    env:
      message: "Hello env"
    runs-on: ubuntu-latest

    steps:
      - uses: MauricioNTT/example-action@main
        with:
          message: Hello Inputs
